apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
  annotations:
    fluxcd.io/ignore: "true"
spec:
  releaseName: sealed-secrets-controller
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: sealed-secrets
    version: 1.3.3
